### ISSUE TITLE
Questions about options and placeholders

### ISSUE THREAD

**Issue by hendersonanalytics** [mazuhl/modx-oembed#1]
Thanks for creating this MODx extra.

I have a few questions about oEmbed 0.2.2-pl

1.) Is the list of placeholders that is in the current README.md document the full list, or do others exist?

2.) What are the possible values for the following option parameters?
&strictMatch
&discover
&outputMode

3.) Are any additional option parameters (besides the ones in the current README.md document) available?

Thanks!

**Comment by mazuhl** [comment]
It's not my Extra, I just repackaged it so it works with the newer versions of MODX.
1. I think it's the full list.
2. README updated, but here they are:

| Parameter | Comments |
| --- | --- |
| &strictMatch | Ignores any other parameters on the request URL |
| &discover | Is some kind of search |
| &outputMode | Either get just the embed code or (using `full` option) wrap it in an HTML block specific to the media type |

The HTML wrapper looks like this:

``` html
<div class="oembed oembed-video" style="width: [[+wrapperWidth]]px">
    [[+embed]]
    <p>[[+title]] by <a href="[[+author_url]]" target="_blank">[[+author_name]]</a></p>
</div>
```
1. I don't think so.

**Comment by hendersonanalytics** [comment]
Thanks dude.
